### ISSUE TITLE
insert with total.js restful2 save method

### ISSUE THREAD

**Issue by dacrhu** [totaljs/node-sqlagent#19]
Hi,
I made a simple "insert" in total.js with r"estful2" save method.

```
    schema.define('email', 'Email', true);
    schema.define('companyid', 'String', true);
    schema.define('role', 'String', true);

    schema.setSave(function(error, model, controller, callback) {
        let db = DB();

        db.insert('user', 'users').make(function(builder) {
            builder.set({
                name: 'Peter',
                age: 30
            });
        });

        db.exec(callback, 0);

    });
```
And I get:

```
500: Internal Server Error :: TypeError: Cannot read property 'query' of undefined
    at Object.fn (/home/dacr/ehs/backend/node_modules/sqlagent/mongodb.js:1008:15)
    at Array.<anonymous> (/home/dacr/ehs/backend/node_modules/sqlagent/mongodb.js:1530:8)
    at Array.sqlagent (/home/dacr/ehs/backend/node_modules/sqlagent/index.js:11:9)
    at Object.Agent._prepare (/home/dacr/ehs/backend/node_modules/sqlagent/mongodb.js:1413:15)
    at /home/dacr/ehs/backend/node_modules/sqlagent/mongodb.js:1613:8
    at connect (/home/dacr/ehs/backend/node_modules/sqlagent/mongodb.js:1622:10)
    at Object.Agent.exec (/home/dacr/ehs/backend/node_modules/sqlagent/mongodb.js:1602:2)
    at SchemaBuilderEntity.onSave (/home/dacr/ehs/backend/models/model-admin-users.js:50:12)
    at /home/dacr/ehs/backend/node_modules/total.js/builders.js:875:10
    at SchemaBuilderEntity.$prepare (/home/dacr/ehs/backend/node_modules/total.js/builders.js:1219:3)
```
"Select" and "exist" working fine.
I do something wrong?

Thank you,
David

**Comment by petersirka** [comment]
Hi @dacrhu,
try to test latest beta `$ npm install sqlagent@beta`.... My mistake.

1000x thank you!

**Comment by dacrhu** [comment]
Thank you, working :)
```
> db.users.find();
{ "_id" : ObjectId("5978efeda5c19a1d89631342"), "name" : "Peter", "age" : 30 }

```

**Comment by petersirka** [comment]
Great. I'm going to publish a new fixed version.
Thank you again!

**Comment by petersirka** [comment]
Published.
