### ISSUE TITLE
Error on mongodb install

### ISSUE THREAD

**Issue by gnetsys** [totaljs/node-sqlagent#9]
I am having a problem with sqlagent.

  ======= 2016-10-23 07:09:26: framework.install('definition') 
  |---> Error: Cannot find module 'mongodb' Error: Cannot find module 'mongodb'
        at Function.Module._resolveFilename (module.js:440:15)
        at Function.Module._load (module.js:388:25)
        at Module.require (module.js:468:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (D:\node-sqlagent\mongodb.js:1:80)
        at Module._compile (module.js:541:32)
        at Object.Module._extensions..js (module.js:550:10)
        at Module.load (module.js:458:32)
        at tryModuleLoad (module.js:417:12)

I installed mongodb as well sqlagent/mongodb and it returns this error! I got the same error when I sqlagent/arango.  I am using symlinks for sqlagent and arango.

**Comment by molda** [comment]
This seems to be an issue with the symlinks more then anything else.
I would recommend to run `npm install mongodb sqlagent` within your app folder instead of using symlinks. If that works you know what's wrong :)
